### ISSUE TITLE
Fail to install lettuce following the documentation on Clime computer

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#54]
Following https://heimdali.readthedocs.org/en/develop/develop.html#install-dependencies I failed to install lettuce:

`pip install lettuce`
fails as it want to write in /usr.

`pip install --user lettuce`
fails too, with the following message:

 Running setup.py install for unittest2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/stockage/climefs1a/bereziat/HEIMDALI/heimdali/tests/build/unittest2/setup.py", line 87, in <module>
        setup(**params)
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 29, in finalize_options
        _install.finalize_options(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 357, in finalize_options
        self.create_home_path()
      File "/usr/lib/python2.7/distutils/command/install.py", line 591, in create_home_path
        if path.startswith(home) and not os.path.isdir(path):
    AttributeError: late_version instance has no attribute 'startswith'
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/stockage/climefs1a/bereziat/HEIMDALI/heimdali/tests/build/unittest2/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-cjx0Ww-record/install-record.txt --user:
    running install

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/stockage/climefs1a/bereziat/HEIMDALI/heimdali/tests/build/unittest2/setup.py", line 87, in <module>

```
setup(**params)
```

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

```
dist.run_commands()
```

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

```
self.run_command(cmd)
```

  File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command

```
cmd_obj.ensure_finalized()
```

  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

```
self.finalize_options()
```

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 29, in finalize_options

```
_install.finalize_options(self)
```

  File "/usr/lib/python2.7/distutils/command/install.py", line 357, in finalize_options

```
self.create_home_path()
```

  File "/usr/lib/python2.7/distutils/command/install.py", line 591, in create_home_path

```
if path.startswith(home) and not os.path.isdir(path):
```

AttributeError: late_version instance has no attribute 'startswith'

---

Command /usr/bin/python -c "import setuptools;**file**='/stockage/climefs1a/bereziat/HEIMDALI/heimdali/tests/build/unittest2/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --record /tmp/pip-cjx0Ww-record/install-record.txt --user failed with error code 1
Storing complete log in /home/ROCQ/clime/bereziat/.pip/pip.log

**Comment by dfroger** [comment]
is pip installed in conda? (`conda list pip`, `which pip`)

`hash -r` may help.

**Comment by bereziat** [comment]
OK for me
